### ISSUE TITLE
Version drop down

### ISSUE THREAD

**Issue by marbar3778** [cosmos/vuepress-theme-cosmos#91]
Provide a dropdown somewhere on the page for different versions. This dropdown can read from docs/versions

**Comment by lovincyrus** [comment]
I remember we had a versioning switcher in our early versions of cosmos docs. I'm not sure why that was removed.

cc: @fadeev @nassdonald

**Comment by fadeev** [comment]
We were not using it, and it wasn't designed, just added in an ad-hoc fashion.

https://github.com/cosmos/vuepress-theme-cosmos/commit/79be2012c3b4ad61b4d64a63922b6508b6e5d79c

**Comment by nassdonald** [comment]
We'd always planned to add it back in, since the architecture of the docs was designed to handle version-switching. It just wasn't a huge priority.

If we were to have a version switcher, do we want to limit the number of versions at all or just show them all? And just to be clear, are these versions of the docs or versions of the SDK? I'm assuming the latter.

**Comment by clevinson** [comment]
I'd love to see this issue prioritized so we can make use of it in the cosmos SDK as well.

We'll definitely be making use of versioning the docs for Cosmos SDK for Stargate, but would be ideal to have this accessible via the UI and be able to set the default to a stable release other than master (which is often pre-release).

**Comment by lovincyrus** [comment]
The official vuepress does not support versioning (https://github.com/vuejs/vuepress/issues/1018)

```
tendermint docs
- master
- 0.33
- 0.32

cosmos sdk docs
- master
- 0.38
- 0.37
```

## Related:
- https://github.com/tendermint/tendermint/pull/5241
- https://github.com/cosmos/vuepress-theme-cosmos/commit/79be2012c3b4ad61b4d64a63922b6508b6e5d79c
- https://github.com/cosmos/cosmos-sdk/issues/6308
- https://github.com/cosmos/vuepress-theme-cosmos/issues/91
- https://github.com/vuejs/vuepress/issues/1018

## Different implementation:
1. ava - https://github.com/avajs/ava/pull/2051
2. lighthouse - https://github.com/vuejs/vuepress/issues/1018#issuecomment-440248700
3. pomerium - https://github.com/pomerium/pomerium/issues/109
4. docs-devkit - https://github.com/appcelerator/docs-devkit/tree/develop/packages/vuepress/vuepress-plugin-versioning#readme

## Next step:
- https://github.com/cosmos/vuepress-theme-cosmos/pull/115#issuecomment-701150872

**Comment by lovincyrus** [comment]
- [ ] after merging https://github.com/cosmos/vuepress-theme-cosmos/pull/115, test it on `docs-staging` branch of cosmos-sdk

### Usage
- uses router push to switch version
- user must add an array of versions to themeConfig in .vuepress/config.js in order to use version switcher
- unable to test it locally even after using make build-docs to generate different versions in ~/output locally

**homepage**
<img width="1445" alt="homepage" src="https://user-images.githubusercontent.com/1021101/99000023-83156a80-24ed-11eb-994f-dd7597d5c6b8.png">

**aside bar**
<img width="1445" alt="aside bar" src="https://user-images.githubusercontent.com/1021101/99000129-a5a78380-24ed-11eb-8b1a-9f61d011fb74.png">

**mobile**
<img width="499" alt="mobile" src="https://user-images.githubusercontent.com/1021101/99000157-acce9180-24ed-11eb-8d21-5f6c6edb8c91.png">

**Comment by marbar3778** [comment]
<img width="126" alt="Screen Shot 2020-12-07 at 12 18 46 PM" src="https://user-images.githubusercontent.com/24299864/101344816-5d7a4780-3886-11eb-8446-81b03265bae0.png">


Is this the intended design? It looks different in the above photos

**Comment by nassdonald** [comment]
No… that doesn't look right. @lovincyrus could this be a cross-browser issue?

`appearance: none;` might be needed here (with vendor prefixes too) to remove the styling of the native `<select>`. Also the text should be the version number, e.g. "v0.40" as the screenshots above.

**Comment by lovincyrus** [comment]
> Also the text should be the version number, e.g. "v0.40" as the screenshots above.

I added a select option disabled Version there instead of showing the version number because of how our versioning deployments were set up. The docs theme is unable to utilize vue router to route to different versions due to the version path prefixes (/master, /v0.34) that are being generated with Makefile. Otherwise, it will go https://docs.cosmos.network/master → https://docs.cosmos.network/master/master

In order to make this work, we need to change the version using window.location with version selection. https://github.com/cosmos/vuepress-theme-cosmos/blob/develop/global-components/TmSelectVersion.vue#L23

That's why we can't show the version text. We're basically refreshing the URL/window history.

**Comment by lovincyrus** [comment]
> @lovincyrus could this be a cross-browser issue?

Most likely. How can I reproduce this?

**Comment by nassdonald** [comment]
Okay in that case, if there's no clean workaround to show the version number, let's just change it to "Version" singular. I think that makes more sense, since it's a **version** selector.

**Comment by lovincyrus** [comment]
https://github.com/cosmos/vuepress-theme-cosmos/issues/175

**Comment by marbar3778** [comment]
Not sure it's possible but is there a way to make it persistent? Right now if you go from master to any version you lose the capability to go back to a different version.

**Comment by lovincyrus** [comment]
> but is there a way to make it persistent?

If you go from `/master` → `/v0.32`, you lose the capability to go back to a different version because there is no version switcher in `/v0.32`. Each version deployment is in its own zone.

We can fix this by adding this to the other versioned docs.

```
    versions: [
      {
        "label": "v0.32",
        "key": "v0.32"
      },
      {
        "label": "v0.33",
        "key": "v0.33"
      },
      {
        "label": "v0.34",
        "key": "v0.34"
      },
      {
        "label": "master",
        "key": "master"
      }
    ],
```

**Comment by marbar3778** [comment]
Could this also be solved by an optional persistent header? the header is out of scope of the docs, the docs can change but the header stays on all the pages.  Not sure how vuepress works and if this is possible?

**Comment by marbar3778** [comment]
This isn't solved. Having only updated versions display the dropdown makes it unusable.

I would propose an entire different direction. Instead of building each version separatly we build them together. 

We create a script to create folders of versions. This would mean we dont switch branches to build docs but only clone the docs into a specific folder, called versions. Then vuepress builds these docs as a single page. This way the dropdown will persist across versions. 

root:
- master
- 0.34
- 0.33
- 0.32

**Comment by lovincyrus** [comment]
With the setup of gathering versioned docs in a single branch:
1. https://github.com/cosmos/cosmos-sdk/tree/gh-pages
2. https://github.com/CosmWasm/docs/tree/gh-pages

It seems like https://github.com/cosmos/gaia/pull/541#issuecomment-759874786 will solve the persistent issue. 🙏

**Comment by marbar3778** [comment]
This won't solve the issue at hand. When you change to a version that doesn't have the dropdown version of the theme it disappears prohibiting you from changing versions any further.

**Comment by lovincyrus** [comment]
Quick update:

Apparently, the docs versioning worked this whole time. But we won't be able to see it with the deployments that use for the docs (S3, Netlify, Gh-pages). All of them would add a trailing slash at the end of the URLs.

I just deployed the content from this branch https://github.com/CosmWasm/docs/tree/gh-pages to Vercel.

Live site: https://docs.cosmwasm.com
Vercel: https://docs-gh-pages.vercel.app

S3, Netlify deployments would automatically add a trailing slash at the end of the URL. Vercel doesn’t. Will push a fix asap.

**Comment by lovincyrus** [comment]
> When you change to a version that doesn't have the dropdown version of the theme it disappears prohibiting you from changing versions any further.

The version you changed to must have an updated `.vuepress/config.js` versions.

**Comment by marbar3778** [comment]
> The version you changed to must have an updated `.vuepress/config.js` versions.

This is bad UX IMO. what is the problem with: 

1. cloning all versions 
2. moving the docs folder into a vX folder
3.  version dropdown picking which folder to display

This way you avoid needing to update old versions.

**Comment by marbar3778** [comment]
I have a demo of what I was thinking here: https://github.com/tendermint/tendermint/pull/5932. The only change needed from the theme would be to display what's in the sidebar based off of what version is chosen. Now they all show up, but the version picker displays the correct version when I go to 0.33 or 0.34

**Comment by marbar3778** [comment]
had a call with cyrus. We agreed the current approach is the best workaround
